### ISSUE TITLE
Comparing `mpipool`'s & `mpi4py`'s `concurrent.futures` implementations

### ISSUE THREAD

**Issue by jakirkham** [mpipool/mpipool#10]
Somewhat recently `mpi4py` started including [a `concurrent.futures` implementation]( https://mpi4py.readthedocs.io/en/stable/mpi4py.futures.html ).

Though IIUC `mpipool` started quite a bit before `mpi4py` added that functionality.

Curious how the two compare in terms of functionality and if there are any notable differences in terms of design decisions.

**Comment by Helveg** [comment]
I think they are mostly similar. `mpi4py`s implementation will for sure be stabler, because they are a larger project with more maintainers. I was hoping to add synchronized error handling, to allow the main node to join the work, to add timeouts, and to detect deadlocks better in this package; but I have no bandwidth to do so.

Thanks for your interest! :)
